name: macOS

on:
    push:
        branches: [master]
        paths-ignore: README.md
    schedule:
        - cron: '0 15 * * 6'
    workflow_dispatch:

jobs:
    Install:
        runs-on: macos-latest
        name: Install macOS
        steps:
            - uses: actions/checkout@v3
            - name: Install
              run: HOMEBREW_BUNDLE_BREW_SKIP="awscli go" HOMEBREW_BUNDLE_CASK_SKIP="zoom chromedriver" /bin/bash ./install.sh
