name: macOS

on:
    push:
        branches: [master]
    workflow_dispatch:

jobs:
    Install:
        runs-on: macos-latest
        name: Install macOS
        steps:
            - uses: actions/checkout@v2
            - name: Install
              run: /bin/bash ./install.sh
