name: Ubuntu

on:
    push:
        branches: [master]
    workflow_dispatch:

jobs:
    Install:
        runs-on: ubuntu-latest
        name: Install Ubuntu
        steps:
            - uses: actions/checkout@v2
            - name: Install
              run: /bin/bash ./install.sh
